"""External-import connector pushing AFRINTEL STIX 2.1 bundles into OpenCTI.

AFRINTEL publishes one STIX 2.1 bundle per completed month at
stix/<year>/<mm-month>/afrintel_<month>_<year>_opencti.json, generated by
scripts/afrintel_victims_to_stix.py from the bilingual victims.md files.

All object IDs in those bundles are deterministic (uuid5, namespaced on the
AFRINTEL repository URL), so re-sending a bundle is safe: OpenCTI updates the
existing objects instead of creating duplicates. This lets the connector
simply resync every known bundle on each run instead of tracking incremental
diffs.
"""

import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List
from urllib.parse import quote

import isodate
import requests
import yaml
from pycti import OpenCTIConnectorHelper, get_config_variable


class AfrintelConnector:
    def __init__(self):
        config_file_path = Path(__file__).parent / "config.yml"
        config = (
            yaml.load(config_file_path.read_text(encoding="utf-8"), Loader=yaml.SafeLoader)
            if config_file_path.is_file()
            else {}
        )

        self.helper = OpenCTIConnectorHelper(config)

        self.source = get_config_variable(
            "AFRINTEL_SOURCE", ["afrintel", "source"], config, default="github"
        ).lower()
        self.repo_path = get_config_variable(
            "AFRINTEL_REPO_PATH", ["afrintel", "repo_path"], config, default="/repo"
        )
        self.github_repo = get_config_variable(
            "AFRINTEL_GITHUB_REPO",
            ["afrintel", "github_repo"],
            config,
            default="Hatchepsoute/AFRINTEL",
        )
        self.github_branch = get_config_variable(
            "AFRINTEL_GITHUB_BRANCH", ["afrintel", "github_branch"], config, default="main"
        )
        self.github_token = get_config_variable(
            "AFRINTEL_GITHUB_TOKEN", ["afrintel", "github_token"], config, default=None
        )
        duration_period = get_config_variable(
            "CONNECTOR_DURATION_PERIOD", ["connector", "duration_period"], config, default="P1D"
        )
        self.duration_period = isodate.parse_duration(duration_period).total_seconds()
        if self.duration_period <= 0:
            raise ValueError("CONNECTOR_DURATION_PERIOD must be greater than zero")
        self.session = requests.Session()
        self.session.headers.update(self._github_headers())

        if self.source not in ("github", "local"):
            raise ValueError(
                f"Invalid AFRINTEL_SOURCE '{self.source}', expected 'github' or 'local'"
            )

    # -- discovery ---------------------------------------------------------

    def _github_headers(self) -> Dict[str, str]:
        headers = {"Accept": "application/vnd.github+json"}
        if self.github_token:
            headers["Authorization"] = f"Bearer {self.github_token}"
        return headers

    def _list_bundle_refs(self) -> List[str]:
        if self.source == "local":
            base = Path(self.repo_path) / "stix"
            return sorted(
                str(path.relative_to(self.repo_path)) for path in base.rglob("*_opencti.json")
            )

        branch = quote(self.github_branch, safe="")
        url = f"https://api.github.com/repos/{self.github_repo}/git/trees/{branch}?recursive=1"
        response = self.session.get(url, timeout=30)
        response.raise_for_status()
        payload = response.json()
        if payload.get("truncated"):
            raise RuntimeError("GitHub returned a truncated repository tree")
        tree = payload.get("tree", [])
        return sorted(
            item["path"]
            for item in tree
            if item.get("type") == "blob"
            and item["path"].startswith("stix/")
            and item["path"].endswith("_opencti.json")
        )

    def _read_bundle(self, ref: str) -> str:
        if self.source == "local":
            return (Path(self.repo_path) / ref).read_text(encoding="utf-8")

        branch = quote(self.github_branch, safe="")
        ref_path = quote(ref, safe="/")
        url = f"https://raw.githubusercontent.com/{self.github_repo}/{branch}/{ref_path}"
        response = self.session.get(url, timeout=30)
        response.raise_for_status()
        return response.text

    # -- processing ----------------------------------------------------------

    def process_message(self) -> None:
        now = datetime.now(timezone.utc)
        friendly_name = f"AFRINTEL import @ {now:%Y-%m-%d %H:%M:%S} UTC"
        work_id = self.helper.api.work.initiate_work(self.helper.connect_id, friendly_name)
        self._current_work_id = work_id
        state = self.helper.get_state() or {}
        processed: Dict[str, str] = dict(state.get("processed_bundles", {}))

        refs = self._list_bundle_refs()
        self.helper.connector_logger.info(f"AFRINTEL: found {len(refs)} STIX bundle file(s) ({self.source})")

        imported = 0
        skipped = 0
        failed = 0

        for ref in refs:
            try:
                content = self._read_bundle(ref)
            except (OSError, requests.RequestException) as exc:
                self.helper.connector_logger.error(f"AFRINTEL: could not fetch {ref}: {exc}")
                failed += 1
                continue

            digest = hashlib.sha256(content.encode("utf-8")).hexdigest()
            if processed.get(ref) == digest:
                skipped += 1
                continue

            try:
                bundle = json.loads(content)
            except json.JSONDecodeError as exc:
                self.helper.connector_logger.error(f"AFRINTEL: invalid JSON in {ref}: {exc}")
                failed += 1
                continue

            if bundle.get("type") != "bundle" or not isinstance(bundle.get("objects"), list):
                self.helper.connector_logger.warning(f"AFRINTEL: skipping non-bundle file {ref}")
                skipped += 1
                continue

            self.helper.connector_logger.info(
                f"AFRINTEL: importing {ref} ({len(bundle.get('objects', []))} objects)"
            )
            self.helper.send_stix2_bundle(
                json.dumps(bundle),
                update=True,
                work_id=work_id,
                cleanup_inconsistent_bundle=True,
            )
            processed[ref] = digest
            imported += 1

        state["processed_bundles"] = processed
        state["last_run"] = datetime.now(timezone.utc).isoformat()
        self.helper.set_state(state)

        message = (
            f"AFRINTEL: {imported} bundle(s) imported, {skipped} unchanged, "
            f"{failed} failed (source={self.source})"
        )
        self.helper.connector_logger.info(message)
        self.helper.api.work.to_processed(work_id, message, failed > 0)

    # -- scheduling ----------------------------------------------------------

    def _scheduled_process(self) -> None:
        try:
            self.process_message()
        except Exception as exc:
            self.helper.connector_logger.error("AFRINTEL import failed", {"error": str(exc)})
            work_id = getattr(self, "_current_work_id", None)
            if work_id:
                self.helper.api.work.to_processed(work_id, str(exc), True)

    def run(self) -> None:
        self.helper.connector_logger.info("Starting AFRINTEL connector")
        self.helper.schedule_process(
            message_callback=self._scheduled_process,
            duration_period=self.duration_period,
        )
